import os
import json
import argparse
import sys
import random
from pathlib import Path
from typing import Any, List, Dict, Optional
import numpy as np



# Add project root to python path to avoid import errors
sys.path.append(str(Path(__file__).resolve().parent.parent))

from edhc.app.config.settings import settings
from edhc.app.schemas.candidate import CandidateProfile, CandidateProfileNormalized, normalize_candidate
from edhc.app.jd.intelligence import JobDescriptionParser
from edhc.app.pipeline.training import TrainingPipeline
from edhc.app.utils.logger import get_logger
from edhc.app.semantic.retrieval import HybridRetrievalEngine

logger = get_logger("train_cli")

def load_processed_candidates(processed_dir: Path) -> list:
    """Load all normalized candidate files from the processed directory."""
    candidates = []
    for file_path in processed_dir.glob("*.json"):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            candidates.append(CandidateProfileNormalized(**data))
        except Exception as e:
            logger.error(f"Failed to load processed candidate {file_path.name}: {e}")
    return candidates

def load_candidates_from_file(file_path: Path, max_samples: int = 2000) -> list:
    """Load candidates from a JSON or JSONL file (either raw or gzipped)."""
    import gzip
    candidates = []
    logger.info(f"Loading up to {max_samples} candidates from {file_path}...")
    
    open_func = gzip.open if file_path.suffix == ".gz" else open
    mode = "rt" if file_path.suffix == ".gz" else "r"
    
    # Read file content to detect if it is a JSON array or JSONL
    with open_func(file_path, mode, encoding="utf-8") as f:
        first_char = ""
        for char in f.read(100):
            if char.strip():
                first_char = char
                break
                
    # Parse based on structure
    with open_func(file_path, mode, encoding="utf-8") as f:
        if first_char == "[":
            # standard JSON array
            data = json.load(f)
            for item in data[:max_samples]:
                candidates.append(CandidateProfile(**item))
        else:
            # JSONL format
            count = 0
            for line in f:
                if not line.strip():
                    continue
                data = json.loads(line)
                candidates.append(CandidateProfile(**data))
                count += 1
                if count >= max_samples:
                    break
                    
    logger.info(f"Loaded total {len(candidates)} candidates from {file_path.name}.")
    return candidates

# --- Dynamic JDs and Configurations ---
DOMAIN_JDS = {
    "ml": ("Senior AI and Machine Learning Engineer", """
        Job Title: Senior AI and Machine Learning Engineer
        Required: Python, PyTorch, machine learning, deep learning, NLP, LLMs, fine-tuning, transformers, PyTorch, scikit-learn.
        Experience: 5+ years.
    """),
    "search": ("Senior Search and Information Retrieval Engineer", """
        Job Title: Senior Search and Information Retrieval Engineer
        Required: Python, search ranking, information retrieval, BM25, vector search, dense retrieval, reranking, learning to rank, LambdaMART, Elasticsearch, Opensearch.
        Experience: 5+ years.
    """),
    "backend": ("Senior Backend and MLOps Engineer", """
        Job Title: Senior Backend and MLOps Engineer
        Required: Python, FastAPI, Docker, Kubernetes, MLOps, microservices, system design, PostgreSQL, AWS, GCP, Redis, CI/CD.
        Experience: 6+ years.
    """),
    "data": ("Senior Data Engineer", """
        Job Title: Senior Data Engineer
        Required: SQL, Spark, ETL, data engineering, python, pandas, polars, bigquery, snowflake, airflow, data warehousing.
        Experience: 5+ years.
    """),
    "frontend": ("Senior Frontend Developer", """
        Job Title: Senior Frontend Developer
        Required: Javascript, React, HTML, CSS, TypeScript, Next.js, Redux, UI/UX, frontend design.
        Experience: 5+ years.
    """)
}

def compute_relevance_label(cand: CandidateProfile, features: Any, domain: str) -> int:
    """Compute a rich, multi-dimensional synthetic relevance label between 0 and 4.
    
    Uses exact candidate features generated by FeatureGenerator.
    """
    score = 0.0
    
    # 1. Domain Specialty Match (0.0 to 1.5)
    # Check domain relevance of candidate profile and resume text
    if domain == "ml":
        ml_score = features.domain_relevance_score * 0.7 + features.jd_title_similarity * 0.5 + features.jd_summary_similarity * 0.3
        score += min(1.5, ml_score)
    elif domain == "search":
        search_score = features.domain_relevance_score * 0.6 + features.jd_title_similarity * 0.6 + features.skill_overlap_ratio * 0.3
        score += min(1.5, search_score)
    elif domain == "backend":
        backend_score = features.product_company_ratio * 0.4 + features.jd_title_similarity * 0.6 + features.skill_overlap_ratio * 0.5
        score += min(1.5, backend_score)
    elif domain == "data":
        data_score = features.domain_relevance_score * 0.4 + features.jd_title_similarity * 0.6 + features.skill_overlap_ratio * 0.5
        score += min(1.5, data_score)
    elif domain == "frontend":
        frontend_score = features.jd_title_similarity * 0.8 + features.skill_overlap_ratio * 0.7
        score += min(1.5, frontend_score)

    # 2. Years of Experience (YOE) Match (0.0 to 1.0)
    yoe = features.relevant_experience_years
    if 5.0 <= yoe <= 15.0:
        score += 1.0
    elif 3.0 <= yoe < 5.0:
        score += 0.5
    elif yoe > 15.0:
        score += 0.7
    else:
        score += 0.0

    # 3. Seniority and Trajectory (0.0 to 0.5)
    seniority = features.leadership_indicator_score * 0.3 + features.promotion_trajectory_score * 0.2
    score += min(0.5, seniority)

    # 4. Evidence Strength & Competency Coverage (0.0 to 0.5)
    evidence = features.evidence_strength * 0.3 + features.competency_coverage * 0.2
    score += min(0.5, evidence)

    # 5. Quantified Achievements & Performance Metric Mentions (0.0 to 0.5)
    achievements = (features.quantitative_achievement_count * 0.05) + (features.performance_metric_mentions * 0.1) + (features.impact_extraction_score * 0.2)
    score += min(0.5, achievements)

    # 6. Cross-Source Corroboration & Skills Verification (0.0 to 0.5)
    corroboration = (features.cross_source_verification_count * 0.05) + (features.skill_diversity_score * 0.2)
    score += min(0.5, corroboration)

    # 7. Retrieval Diagnostics (0.0 to 0.5)
    retrieval = (features.dense_retrieval_score * 0.4) + (features.retrieval_rank_percentile * 0.2)
    score += min(0.5, retrieval)

    # 8. Irrelevant profile / Low credibility penalties
    current_title = cand.profile.current_title.lower()
    summary = cand.profile.summary.lower()
    irrelevant_keywords = ["designer", "graphic", "hr", "recruiter", "sales", "marketing", "accountant", "mechanical", "civil", "qa", "testing", "product manager", "scrum master"]
    if any(kw in current_title for kw in irrelevant_keywords) or any(kw in summary for kw in ["recruiting", "human resources", "marketing specialist"]):
        score -= 2.5
        
    if features.credibility_score < 0.7 or features.contradiction_count > 0:
        score -= 1.0

    label = int(round(score))
    return min(4, max(0, label))

def check_feature_consistency(X: np.ndarray, feature_names: list, candidates: list, jd, feature_generator):
    """Verify that feature ordering is deterministic, count matches inference, no NaNs/Infs exist,
    and identical candidates map to identical vectors.
    """
    logger.info("Running feature consistency checks...")
    
    # 1. Feature count check
    n_features = X.shape[1]
    expected_features = len(feature_names)
    if n_features != expected_features:
        err_msg = f"Feature dimension mismatch: expected {expected_features} features, got {n_features}."
        logger.error(err_msg)
        raise AssertionError(err_msg)
        
    # 2. NaN/Inf check
    if np.isnan(X).any():
        err_msg = "NaN values found in the feature matrix."
        logger.error(err_msg)
        raise AssertionError(err_msg)
        
    if np.isinf(X).any():
        err_msg = "Infinite values found in the feature matrix."
        logger.error(err_msg)
        raise AssertionError(err_msg)
        
    # 3. Determinism check
    if candidates:
        cand = candidates[0]
        diag = {
            "bm25_score": 10.0,
            "bm25_rank": 1,
            "dense_similarity": 0.8,
            "dense_rank": 1,
            "rrf_score": 0.8,
            "rrf_rank": 1
        }
        feat1 = feature_generator.generate(cand, jd, 0.8, retrieval_diag=diag)
        feat2 = feature_generator.generate(cand, jd, 0.8, retrieval_diag=diag)
        
        if not np.allclose(feat1.to_array(), feat2.to_array()):
            err_msg = "Non-deterministic feature generation: identical candidates produced different vectors."
            logger.error(err_msg)
            raise AssertionError(err_msg)
            
    logger.info("Feature consistency check PASSED. All validations are correct.")

def main():
    parser = argparse.ArgumentParser(description="Train the Learning-to-Rank LambdaMART model.")
    parser.add_argument("--candidates", type=str, default="", help="Path to candidates.jsonl, candidates.json or candidates.jsonl.gz")
    parser.add_argument("--processed-dir", type=str, default=str(settings.PROCESSED_DATA_DIR), help="Path to normalized candidates directory")
    parser.add_argument("--sample-size", type=int, default=5000, help="Maximum candidates to load from file for training")
    parser.add_argument("--retrieval-limit", type=int, default=3000, help="Retrieval limit per query group")
    parser.add_argument("--training-domains", type=str, default="ml,search,backend,data", help="Comma-separated training domains")
    parser.add_argument("--model-out", type=str, default=str(settings.MODELS_DIR / "lambdamart_model.pkl"), help="Path to save the model file")
    
    args = parser.parse_args()
    
    # Document runtime implications
    logger.info("=======================================================================")
    logger.info("Runtime implication notice:")
    logger.info(f"Using sample-size={args.sample_size} and retrieval-limit={args.retrieval_limit}.")
    logger.info("Extracting features on a larger pool exposes the model to border candidates")
    logger.info("and increases quality, but feature extraction might take 1-2 minutes.")
    logger.info("=======================================================================")
    
    candidates = []
    
    # 1. Load candidates from specified file if provided
    if args.candidates:
        cand_path = Path(args.candidates)
        if cand_path.exists():
            candidates = load_candidates_from_file(cand_path, max_samples=args.sample_size)
        else:
            logger.error(f"Specified candidates path does not exist: {cand_path}")
            sys.exit(1)
            
    # 2. Fallback: load from processed-dir if it exists and has JSON files
    if not candidates:
        processed_path = Path(args.processed_dir)
        if processed_path.exists() and any(processed_path.glob("*.json")):
            logger.info(f"Loading candidates from processed directory: {processed_path}")
            candidates = load_processed_candidates(processed_path)
            
    # 3. Fallback: check standard paths
    if not candidates:
        for standard_path_str in [
            "hackathon_assets/sample_candidates.json",
            "hackathon_assets/candidates.jsonl"
        ]:
            standard_path = Path(standard_path_str)
            if standard_path.exists():
                logger.info(f"No candidates loaded. Found standard dataset at {standard_path_str}. Loading...")
                candidates = load_candidates_from_file(standard_path, max_samples=args.sample_size)
                break
                
    if not candidates:
        logger.error("No candidates found to train on. Please specify a valid --candidates file or place processed candidates.")
        sys.exit(1)

    logger.info(f"Normalizing and prepping {len(candidates)} candidates for index...")
    candidate_profiles = [normalize_candidate(c) for c in candidates]
    candidates_map = {c.candidate_id: c for c in candidate_profiles}

    # Initialize retrieval engine and build indices
    retrieval_engine = HybridRetrievalEngine()
    retrieval_engine.index(candidate_profiles)

    # Parse configured JDs
    jd_parser = JobDescriptionParser()
    selected_domains = [d.strip().lower() for d in args.training_domains.split(",") if d.strip()]
    
    jds = []
    qid = 1
    for domain in selected_domains:
        if domain in DOMAIN_JDS:
            title, jd_text = DOMAIN_JDS[domain]
            parsed_jd = jd_parser.parse(jd_text, title)
            jds.append((parsed_jd, domain, qid))
            qid += 1
            
    if not jds:
        logger.error(f"No valid training domains parsed from: {args.training_domains}")
        sys.exit(1)

    train_samples = []
    
    from edhc.app.features.generator import FeatureGenerator
    feature_generator = FeatureGenerator()
    feature_names = feature_generator.generate(candidate_profiles[0], jds[0][0]).get_feature_names()

    for jd, domain, q_id in jds:
        logger.info(f"Generating training data for query group {q_id}: {jd.title} ({domain})")
        q_text = jd_parser.generate_retrieval_query(jd)
        
        # Search the loaded pool using BM25 + Dense RRF
        search_limit = min(len(candidate_profiles), args.retrieval_limit)
        retrieval_results = dict(retrieval_engine.search(q_text, top_k=search_limit))
        diags = retrieval_engine.diagnostics_cache

        # Add retrieved candidates with populated retrieval diagnostics
        for cid, rrf_score in retrieval_results.items():
            cand = candidates_map[cid]
            diag = diags.get(cid)
            
            # Generate features first to compute relevance label
            features = feature_generator.generate(cand, jd, rrf_score, retrieval_diag=diag)
            label = compute_relevance_label(cand, features, domain)
            
            train_samples.append({
                "candidate": cand,
                "jd": jd,
                "label": label,
                "query_id": q_id,
                "retrieval_score": rrf_score,
                "retrieval_diag": diag
            })

        # Add some random negatives (candidates that weren't retrieved)
        non_retrieved = [c for c in candidate_profiles if c.candidate_id not in retrieval_results]
        random.seed(42)
        neg_subset = random.sample(non_retrieved, min(len(non_retrieved), 100)) if non_retrieved else []
        
        for cand in neg_subset:
            diag = {
                "bm25_score": 0.0,
                "bm25_rank": len(candidate_profiles),
                "dense_similarity": 0.0,
                "dense_rank": len(candidate_profiles),
                "rrf_score": 0.0,
                "rrf_rank": len(candidate_profiles)
            }
            # Generate features to calculate label
            features = feature_generator.generate(cand, jd, 0.0, retrieval_diag=diag)
            label = compute_relevance_label(cand, features, domain)
            
            train_samples.append({
                "candidate": cand,
                "jd": jd,
                "label": label,
                "query_id": q_id,
                "retrieval_score": 0.0,
                "retrieval_diag": diag
            })

    logger.info(f"Built LTR dataset with {len(train_samples)} total samples across {len(jds)} queries.")

    # Split train/validation 80/20 per query group
    import numpy as np
    random.seed(42)
    train_samples_split = []
    val_samples_split = []
    
    for _, _, q_id in jds:
        q_samples = [s for s in train_samples if s["query_id"] == q_id]
        random.shuffle(q_samples)
        split_idx = int(len(q_samples) * 0.8)
        train_samples_split.extend(q_samples[:split_idx])
        val_samples_split.extend(q_samples[split_idx:])
        
    logger.info(f"Split data into {len(train_samples_split)} training samples and {len(val_samples_split)} validation samples.")

    # Extract training feature vectors
    X_train_list = []
    y_train = []
    qids_train = []
    
    for sample in train_samples_split:
        cand = sample["candidate"]
        jd = sample["jd"]
        label = sample["label"]
        q_id = sample["query_id"]
        rrf = sample["retrieval_score"]
        diag = sample["retrieval_diag"]
        
        feat = feature_generator.generate(cand, jd, rrf, retrieval_diag=diag)
        X_train_list.append(feat.to_array())
        y_train.append(label)
        qids_train.append(q_id)
        
    X_train = np.vstack(X_train_list)
    y_train = np.array(y_train, dtype=np.int32)
    qids_train = np.array(qids_train, dtype=np.int32)

    # Perform feature consistency check on training set
    check_feature_consistency(X_train, feature_names, candidate_profiles, jds[0][0], feature_generator)

    # Extract validation feature vectors
    X_val_list = []
    y_val = []
    qids_val = []
    
    for sample in val_samples_split:
        cand = sample["candidate"]
        jd = sample["jd"]
        label = sample["label"]
        q_id = sample["query_id"]
        rrf = sample["retrieval_score"]
        diag = sample["retrieval_diag"]
        
        feat = feature_generator.generate(cand, jd, rrf, retrieval_diag=diag)
        X_val_list.append(feat.to_array())
        y_val.append(label)
        qids_val.append(q_id)
        
    X_val = np.vstack(X_val_list)
    y_val = np.array(y_val, dtype=np.int32)
    qids_val = np.array(qids_val, dtype=np.int32)

    # Initialize and train LambdaMARTRanker
    from edhc.app.ranking.ranker import LambdaMARTRanker
    ranker = LambdaMARTRanker()
    
    try:
        ranker.train(X_train, y_train, qids_train)
        
        # Save model
        resolved_save_path = Path(args.model_out)
        resolved_save_path.parent.mkdir(parents=True, exist_ok=True)
        ranker.save(str(resolved_save_path))
        logger.info(f"Training pipeline executed successfully. Model saved to: {resolved_save_path}")
    except Exception as e:
        logger.error(f"Training pipeline execution failed: {e}")
        sys.exit(1)

    # Sanity checks and validation scoring
    try:
        val_preds = ranker.predict(X_val)
        val_variance = float(np.var(val_preds))
        val_min = float(np.min(val_preds))
        val_max = float(np.max(val_preds))
        
        logger.info("=== Validation Set Sanity Checks ===")
        logger.info(f"Validation Predictions Var: {val_variance:.4f}")
        logger.info(f"Validation Predictions Range: [{val_min:.4f}, {val_max:.4f}]")
        
        if val_variance < 1e-4:
            err_msg = f"Sanity check FAILED: predictions are constant or near-constant (variance: {val_variance:.6f})."
            logger.error(err_msg)
            raise AssertionError(err_msg)
            
        if val_max - val_min < 0.1:
            err_msg = f"Sanity check FAILED: score range is too small ({val_max - val_min:.4f})."
            logger.error(err_msg)
            raise AssertionError(err_msg)
            
        # Check ordering direction
        order_checks_passed = 0
        order_checks_failed = 0
        
        for _, _, q_id in jds:
            mask = qids_val == q_id
            q_preds = val_preds[mask]
            q_labels = y_val[mask]
            
            for i in range(len(q_preds)):
                for j in range(len(q_preds)):
                    if q_labels[i] > q_labels[j] + 1:
                        if q_preds[i] > q_preds[j]:
                            order_checks_passed += 1
                        else:
                            order_checks_failed += 1
                            
        total_checks = order_checks_passed + order_checks_failed
        if total_checks > 0:
            pass_ratio = order_checks_passed / total_checks
            logger.info(f"Ordering check: {order_checks_passed} passed, {order_checks_failed} failed (accuracy: {pass_ratio * 100:.2f}%)")
            if pass_ratio < 0.6:
                err_msg = f"Sanity check FAILED: ordering check accuracy is too low ({pass_ratio * 100:.2f}%)."
                logger.error(err_msg)
                raise AssertionError(err_msg)
        else:
            logger.warning("No comparable pairs found in validation set for ordering checks.")
            
        logger.info("Validation set sanity checks PASSED.")
    except Exception as e:
        logger.error(f"Sanity check failed: {e}")
        sys.exit(1)

    # Detailed Post-Training Diagnostics
    try:
        train_preds = ranker.predict(X_train)
        train_variance = float(np.var(train_preds))
        
        unique_labels, counts = np.unique(y_train, return_counts=True)
        label_dist = dict(zip(unique_labels.tolist(), counts.tolist()))
        total_train = len(y_train)
        
        logger.info("=== LTR Model Post-Training Diagnostics ===")
        logger.info(f"Candidates loaded: {len(candidates)}")
        logger.info(f"Training samples: {total_train}")
        logger.info(f"Validation samples: {len(y_val)}")
        logger.info(f"Query groups used: {np.unique(qids_train).tolist()}")
        logger.info(f"Label distribution: {label_dist}")
        logger.info(f"Training Prediction Variance: {train_variance:.4f}")
        
        # Imbalance warning
        for label, count in label_dist.items():
            ratio = count / total_train
            if ratio > 0.9:
                logger.warning(f"WARNING: Labels are heavily imbalanced. Label {label} constitutes {ratio * 100:.2f}% of samples.")
                
        # Predictions collapse warning
        if train_variance < 1e-4:
            logger.warning(f"WARNING: All training predictions are nearly identical (variance: {train_variance:.6f}). Model might be collapsed.")
            
        # Feature Importance
        importances = ranker.model.feature_importances_
        sorted_features = sorted(zip(feature_names, importances), key=lambda x: x[1], reverse=True)
        
        logger.info("\n=== Top 20 Most Important Features ===")
        for idx, (feat, imp) in enumerate(sorted_features[:20], 1):
            logger.info(f"{idx:02d}. Feature: {feat:<35} | Importance: {imp}")
            
        # Feature collapse warning
        total_importance = sum(importances)
        if total_importance > 0:
            top_2_sum = sorted_features[0][1] + sorted_features[1][1]
            top_2_ratio = top_2_sum / total_importance
            if top_2_ratio > 0.95:
                logger.warning(f"WARNING: Feature importance collapses to a few features. Top 2 features account for {top_2_ratio * 100:.2f}% of total importance.")
                
        num_trees = ranker.model.booster_.num_trees()
        logger.info(f"Number of trees: {num_trees}")
    except Exception as e:
        logger.error(f"Failed to log detailed diagnostics: {e}")

if __name__ == "__main__":
    main()
